### ISSUE TITLE
Cannot join

### ISSUE THREAD

**Issue by NMertsch** [van-den-Berg/schweinehund_bot#3]
When I execute `/join`, the bot responds with
> Diese Gruppe steht nicht in der whitelist. Bitte kontaktiere die Administratoren. Die fehlende GruppenID ist -1001766680538.

**Comment by van-den-Berg** [comment]
This issue was solved with commit a7564be590d351039f2795ed786e007bb285909c.

Feel free to reopen this issue if you have further problems regarding this topic.
